openapi: 3.0.0
info:
  title: New API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /some/path:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-some-path
  /new:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-new
components:
  schemas: {}
